version: '3.8'

services:
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8080:8080" # Keycloak port
      - "8082:8082" # main app port
      - "8081:8081"
      - "5432:5432"
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: shop-db-4
    restart: always
    environment:
      POSTGRES_DB: shop_db_v4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "service:localhost"

  redis:
    image: redis:7-alpine
    container_name: shop-redis-4
#    restart: always
    network_mode: "service:localhost"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-server
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    network_mode: "service:localhost"

  payment-service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    container_name: shop-payment-service
    depends_on:
      - keycloak
      - db
#    restart: always
    network_mode: "service:localhost"

  app:
    build:
      context: ./main_module
      dockerfile: Dockerfile
    container_name: shop-app-4
    depends_on:
      - keycloak
      - db
      - redis
      - payment-service
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop_db_v4 #use localhost instead
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
#      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/shop_db_v4
#      SPRING_FLYWAY_USER: postgres
#      SPRING_FLYWAY_PASSWORD: postgres
#      PAYMENT_SERVICE_URL: http://payment-service:8081
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#    restart: always
    network_mode: "service:localhost"

volumes:
  postgres_data: