version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: shop-db-2
    restart: always
    environment:
      POSTGRES_DB: shop_db_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-app-2
    depends_on:
      - db
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop_db_v2
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
#      SPRING_FLYWAY_ENABLED: "true"
#      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/shop_db_v2
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
#      SPRING_FLYWAY_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: