spring:
  application:
    name: payment_service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop_db_v4
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/internet-shop

server:
  port: 8081

payment:
  initial-balance: 5000.00