version: '3.8'

# this docker-compose is used for local development

services:
  db:
    image: postgres:latest
    container_name: shop-db-4-improvements
    restart: always
    environment:
      POSTGRES_DB: shop_db_v4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shop-redis-4-improvements
    restart: always
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-server-improvements
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

volumes:
  postgres_data: