spring:
  application:
    name: internet_shop_project

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop_v2_db
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/shop_v2_db
    password: postgres
    user: postgres
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    encoding: UTF-8
    mode: HTML